name: flutter_template
description: A Flutter skeleton using Clean Architecture, the Bloc state management solution and Sembast.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

# MAJOR version when you make incompatible API changes
# MINOR version when you add functionality in a backwards compatible manner
# PATCH version when you make backwards compatible bug fixes
# + build version
version: 0.0.1+1

environment:
  # this is the dart sdk version
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animations: 2.0.8
  connectivity_plus: 5.0.2
  dart_bloc_concurrency: 1.1.0
  dart_extensionz: 6.2.0
  device_info_plus: 9.1.1 # new versions require Java 17 and Gradle 8.4
  equatable: 2.0.5
  file_selector: 1.0.3
  firebase_core: 2.24.2
  firebase_crashlytics: 3.4.9
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.5
  flutter_extensionz: 4.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: 2.3.7
  flutter_themez: 2.0.9
  flutter_widgetz: 9.5.1
  get_it: 7.6.7
  http: 1.1.0
  image_picker: 1.0.7
  package_info_plus: 4.2.0
  path: 1.8.3
  path_provider: 2.1.3
  permission_handler: 11.0.1
  sembast: 3.6.0
  sembast_web: 2.2.0
  stream_transform: 2.1.0

dev_dependencies:
  bloc_test: 9.1.7
  change_app_package_name: 1.1.0
  dart_lintz: 1.2.1
  flutter_app_name:
    git: https://github.com/mj12358/flutter-app-name
  flutter_launcher_icons: 0.13.1
  flutter_test:
    sdk: flutter
  mocktail: 1.0.3

flutter_app_name:
  name: "flutter_template"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/welcome/
    - assets/logos/

  fonts:
    - family: Primary
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

# dart run flutter_launcher_icons:main
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/launcher.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logos/launcher.png"
  remove_alpha_ios: true

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logos/splash.png
  android: true
  ios: true
  web: true
  fullscreen: true
