name: flutter_template
description: A Flutter skeleton using Clean Architecture, the Bloc state management solution and Sembast.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

# MAJOR version when you make incompatible API changes
# MINOR version when you add functionality in a backwards compatible manner
# PATCH version when you make backwards compatible bug fixes
# + build version
version: 0.0.1+1

environment:
  # this is the dart sdk version
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  dart_extensionz: ^4.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_extensionz: ^2.2.0
  flutter_localizations:
    sdk: flutter
  flutter_themez: ^1.0.6
  get_it: ^7.2.0
  intl: ^0.17.0
  path_provider: ^2.0.13
  sembast: ^3.4.1+1

dev_dependencies:
  bloc_test: ^9.1.1
  change_app_package_name: ^1.1.0
  dart_lintz: ^1.0.0
  # flutter_app_name: ^0.1.1 # they need to update dependencies
  flutter_app_name:
    git: https://github.com/qixotic/flutter_app_name
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter_app_name:
  name: "flutter_template"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
