name: flutter_template
description: A Flutter skeleton using Clean Architecture, the Bloc state management solution and Sembast.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

# MAJOR version when you make incompatible API changes
# MINOR version when you add functionality in a backwards compatible manner
# PATCH version when you make backwards compatible bug fixes
# + build version
version: 0.0.1+1

environment:
  # this is the dart sdk version
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  connectivity_plus: ^4.0.2
  dart_extensionz: ^4.6.0
  device_info_plus: ^9.0.3
  equatable: ^2.0.5
  firebase_analytics: ^10.4.5
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_extensionz: ^3.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_themez: ^1.2.1
  flutter_widgetz: ^5.1.1
  get_it: ^7.6.0
  http: ^1.1.0
  intl: ^0.18.0
  package_info_plus: ^4.1.0
  path_provider: ^2.1.1
  sembast: ^3.5.0+1
  stream_transform: ^2.1.0

dev_dependencies:
  bloc_test: ^9.1.4
  change_app_package_name: ^1.1.0
  dart_lintz: ^1.2.0
  # flutter_app_name: ^0.1.1 # they need to update dependencies
  # flutter_app_name:
  #   git: https://github.com/qixotic/flutter_app_name
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter_app_name:
  name: "flutter_template"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/logos/
