name: Mark stale issues

on:
  schedule:
    - cron: "16 10 * * 1"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/stale@v5
        with:
          days-before-stale: ${{ vars.DAYS_BEFORE_STALE }}
          days-before-close: ${{ vars.DAYS_BEFORE_CLOSE }}
          stale-issue-message: "This issue is stale because it has been open for ${{ vars.DAYS_BEFORE_STALE }} days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for ${{ vars.DAYS_BEFORE_CLOSE }} days since being marked as stale."
          stale-issue-label: "Stale"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
